export const emojis = [
	{
		name: "Gestures",
		emojis: [
			{ emoji: "👋", keywords: "wave hello goodbye hand greeting welcome" },
			{ emoji: "🤚", keywords: "raised hand stop halt high five" },
			{ emoji: "🖐️", keywords: "hand fingers spread high five stop" },
			{ emoji: "✋", keywords: "raised hand stop halt high five" },
			{
				emoji: "🖖",
				keywords: "vulcan spock star trek hand live long prosper",
			},
			{ emoji: "👌", keywords: "ok hand perfect agree approve" },
			{ emoji: "🤌", keywords: "pinched fingers italian hand what chef kiss" },
			{ emoji: "🤏", keywords: "pinching hand small tiny little bit" },
			{ emoji: "✌️", keywords: "victory hand peace fingers v sign" },
			{ emoji: "🤞", keywords: "crossed fingers luck hopeful wishing" },
			{ emoji: "🤟", keywords: "love you gesture hand rock ily" },
			{ emoji: "🤘", keywords: "rock on hand horns sign metal music" },
			{
				emoji: "🤙",
				keywords: "call me hand phone telephone hang loose shaka",
			},
			{ emoji: "👈", keywords: "point left hand direction finger" },
			{ emoji: "👉", keywords: "point right hand direction finger" },
			{ emoji: "👆", keywords: "point up hand direction finger" },
			{ emoji: "🖕", keywords: "middle finger hand rude offensive" },
			{ emoji: "👇", keywords: "point down hand direction finger" },
			{ emoji: "☝️", keywords: "point up index hand direction finger" },
			{ emoji: "👍", keywords: "thumbs up like approve agree good positive" },
			{ emoji: "👎", keywords: "thumbs down dislike disapprove bad negative" },
			{ emoji: "✊", keywords: "raised fist power strength solidarity" },
			{ emoji: "👊", keywords: "fist bump punch hit" },
			{ emoji: "🤛", keywords: "left fist bump punch hit" },
			{ emoji: "🤜", keywords: "right fist bump punch hit" },
			{
				emoji: "👏",
				keywords: "clapping hands applause praise congratulations",
			},
			{
				emoji: "🙌",
				keywords: "raised hands celebration hooray praise worship",
			},
			{ emoji: "👐", keywords: "open hands offering welcome" },
			{ emoji: "🤲", keywords: "palms up together prayer please beg" },
			{
				emoji: "🙏",
				keywords: "folded hands prayer please thank you hope wish",
			},
			{ emoji: "✍️", keywords: "writing hand write note signature" },
			{ emoji: "💅", keywords: "nail polish manicure beauty self-care" },
			{ emoji: "🤳", keywords: "selfie photo camera phone" },
		],
	},
	{
		name: "Objects",
		emojis: [
			{ emoji: "❤️", keywords: "red heart love like romance valentine" },
			{ emoji: "🧡", keywords: "orange heart love like friendship" },
			{ emoji: "💛", keywords: "yellow heart love like friendship joy" },
			{ emoji: "💚", keywords: "green heart love like jealousy nature" },
			{ emoji: "💙", keywords: "blue heart love like trust loyalty" },
			{ emoji: "💜", keywords: "purple heart love like imagination magic" },
			{ emoji: "🖤", keywords: "black heart love like goth mystery" },
			{ emoji: "🤍", keywords: "white heart love like pure clean" },
			{ emoji: "🤎", keywords: "brown heart love like warm cozy" },
			{ emoji: "💔", keywords: "broken heart heartbreak sad pain breakup" },
			{ emoji: "❤️‍🔥", keywords: "heart on fire love passion desire burning" },
			{ emoji: "❤️‍🩹", keywords: "mending heart healing recovery love" },
			{ emoji: "💯", keywords: "hundred points perfect score excellent" },
			{ emoji: "💢", keywords: "anger symbol mad angry irritated" },
			{ emoji: "💬", keywords: "speech balloon message chat talking" },
			{ emoji: "👁️‍🗨️", keywords: "eye in speech bubble witness testimony" },
			{ emoji: "🕳️", keywords: "hole empty dark void" },
			{ emoji: "💤", keywords: "zzz sleeping tired snoring nap" },
			{ emoji: "💮", keywords: "white flower japanese symbol well done" },
			{ emoji: "♨️", keywords: "hot springs steaming warm bath spa" },
			{ emoji: "💈", keywords: "barber pole haircut salon" },
			{ emoji: "🛑", keywords: "stop sign octagon traffic halt" },
			{ emoji: "🕰️", keywords: "mantelpiece clock time antique vintage" },
			{ emoji: "🌡️", keywords: "thermometer temperature hot cold weather" },
			{ emoji: "🧿", keywords: "nazar amulet evil eye protection luck" },
			{
				emoji: "🎁",
				keywords: "wrapped gift present birthday surprise package",
			},
			{ emoji: "🎊", keywords: "confetti ball celebration party festival" },
			{
				emoji: "🎉",
				keywords: "party popper celebration hooray surprise tada",
			},
		],
	},
	{
		name: "Activities",
		emojis: [
			{ emoji: "🎮", keywords: "video game controller gaming play fun" },
			{ emoji: "🎲", keywords: "game die dice gambling board games random" },
			{ emoji: "♟️", keywords: "chess pawn board game strategy" },
			{ emoji: "🎯", keywords: "direct hit target bullseye dart accuracy" },
			{ emoji: "🎳", keywords: "bowling strike spare pins ball" },
			{ emoji: "🎭", keywords: "performing arts theater drama masks acting" },
			{ emoji: "🎨", keywords: "artist palette painting draw art creative" },
			{ emoji: "🎬", keywords: "clapper board movie film action cinema" },
			{ emoji: "🎤", keywords: "microphone singing karaoke performance" },
			{ emoji: "🎧", keywords: "headphone music listen audio sound" },
			{ emoji: "🎼", keywords: "musical score sheet music notes compose" },
			{ emoji: "🎹", keywords: "musical keyboard piano instrument play" },
			{ emoji: "🥁", keywords: "drum percussion instrument music beat" },
			{ emoji: "🎷", keywords: "saxophone jazz instrument music" },
			{ emoji: "🎺", keywords: "trumpet instrument music fanfare" },
			{ emoji: "🎸", keywords: "guitar instrument music rock acoustic" },
			{ emoji: "🪕", keywords: "banjo instrument music country folk" },
			{ emoji: "🎻", keywords: "violin classical instrument music orchestra" },
			{ emoji: "🎪", keywords: "circus tent entertainment carnival" },
			{ emoji: "🎟️", keywords: "admission tickets event concert show" },
			{ emoji: "🎫", keywords: "ticket admission event pass" },
			{ emoji: "⚽", keywords: "soccer ball football sport" },
			{ emoji: "⚾", keywords: "baseball sport ball game" },
			{ emoji: "🏀", keywords: "basketball sport ball game" },
			{ emoji: "🏐", keywords: "volleyball sport ball game" },
			{ emoji: "🏈", keywords: "american football sport ball game" },
			{ emoji: "🏉", keywords: "rugby football sport ball game" },
			{ emoji: "🎾", keywords: "tennis sport ball game" },
			{ emoji: "🥏", keywords: "flying disc frisbee sport ultimate" },
			{ emoji: "🏏", keywords: "cricket game sport ball bat" },
			{ emoji: "🏑", keywords: "field hockey sport stick ball" },
			{ emoji: "🏒", keywords: "ice hockey sport stick puck" },
			{ emoji: "🥍", keywords: "lacrosse sport stick ball" },
			{ emoji: "🏓", keywords: "ping pong table tennis sport paddle ball" },
			{ emoji: "🏸", keywords: "badminton racquet sport shuttle" },
			{ emoji: "🥊", keywords: "boxing glove sport fight punch" },
			{ emoji: "🥋", keywords: "martial arts uniform karate judo taekwondo" },
			{ emoji: "🥅", keywords: "goal net hockey soccer" },
			{ emoji: "⛳", keywords: "flag in hole golf sport" },
			{ emoji: "⛸️", keywords: "ice skate figure skating sport winter" },
			{ emoji: "🎣", keywords: "fishing pole fish catch sport" },
			{ emoji: "🤿", keywords: "diving mask snorkel swim underwater" },
			{ emoji: "🎽", keywords: "running shirt athletics sport" },
			{ emoji: "🎿", keywords: "skis skiing winter sport snow" },
			{ emoji: "🛷", keywords: "sled sledding winter snow sport" },
			{ emoji: "🥌", keywords: "curling stone sport ice winter" },
		],
	},
	{
		name: "Nature",
		emojis: [
			{
				emoji: "🌱",
				keywords: "seedling plant growth sprout new beginnings nature",
			},
			{ emoji: "🌲", keywords: "evergreen tree pine forest woods nature" },
			{ emoji: "🌳", keywords: "deciduous tree forest woods nature shade" },
			{
				emoji: "🌴",
				keywords: "palm tree tropical beach coconut island vacation",
			},
			{ emoji: "🌵", keywords: "cactus desert plant dry succulent southwest" },
			{ emoji: "🌾", keywords: "sheaf of rice grain crop harvest farm" },
			{ emoji: "🌿", keywords: "herb plant leaf green spice seasoning" },
			{ emoji: "☘️", keywords: "shamrock irish luck ireland clover" },
			{ emoji: "🍀", keywords: "four leaf clover luck fortunate irish" },
			{ emoji: "🍁", keywords: "maple leaf canada fall autumn" },
			{ emoji: "🍂", keywords: "fallen leaf autumn fall foliage" },
			{ emoji: "🍃", keywords: "leaf fluttering in wind breeze nature" },
			{
				emoji: "🌍",
				keywords: "globe showing europe-africa world earth planet",
			},
			{ emoji: "🌎", keywords: "globe showing americas world earth planet" },
			{
				emoji: "🌏",
				keywords: "globe showing asia-australia world earth planet",
			},
			{ emoji: "🌑", keywords: "new moon dark night sky" },
			{ emoji: "🌒", keywords: "waxing crescent moon night sky" },
			{ emoji: "🌓", keywords: "first quarter moon night sky" },
			{ emoji: "🌔", keywords: "waxing gibbous moon night sky" },
			{ emoji: "🌕", keywords: "full moon night sky werewolf" },
			{ emoji: "🌖", keywords: "waning gibbous moon night sky" },
			{ emoji: "🌗", keywords: "last quarter moon night sky" },
			{ emoji: "🌘", keywords: "waning crescent moon night sky" },
			{ emoji: "🌙", keywords: "crescent moon night sky" },
			{ emoji: "🌚", keywords: "new moon face night sky" },
			{ emoji: "🌛", keywords: "first quarter moon face night sky" },
			{ emoji: "🌜", keywords: "last quarter moon face night sky" },
			{ emoji: "☀️", keywords: "sun sunny bright hot solar summer" },
			{ emoji: "🌝", keywords: "full moon face bright night sky" },
			{ emoji: "🌞", keywords: "sun with face summer hot bright" },
			{ emoji: "⭐", keywords: "star night sky shine bright astronomy" },
			{ emoji: "🌟", keywords: "glowing star shine sparkle bright" },
			{ emoji: "🌠", keywords: "shooting star falling wish meteor" },
			{ emoji: "☁️", keywords: "cloud sky weather" },
			{ emoji: "⛅", keywords: "sun behind cloud partly cloudy weather" },
			{ emoji: "⛈️", keywords: "cloud with lightning and rain storm weather" },
			{ emoji: "🌤️", keywords: "sun behind small cloud weather" },
			{ emoji: "🌥️", keywords: "sun behind large cloud weather" },
			{ emoji: "🌦️", keywords: "sun behind rain cloud weather shower" },
			{ emoji: "🌧️", keywords: "cloud with rain weather shower" },
			{ emoji: "🌨️", keywords: "cloud with snow weather winter" },
			{ emoji: "🌩️", keywords: "cloud with lightning weather storm" },
			{ emoji: "🌪️", keywords: "tornado weather destructive cyclone" },
			{ emoji: "🌫️", keywords: "fog weather mist hazy" },
			{ emoji: "🌬️", keywords: "wind face blowing breeze air" },
			{ emoji: "🌈", keywords: "rainbow gay pride rain colorful" },
			{ emoji: "☂️", keywords: "umbrella rain protection weather" },
			{ emoji: "☔", keywords: "umbrella with rain drops weather protection" },
			{ emoji: "⚡", keywords: "high voltage lightning flash electricity" },
			{ emoji: "❄️", keywords: "snowflake winter cold snow" },
			{ emoji: "☃️", keywords: "snowman winter snow cold frosty" },
			{ emoji: "⛄", keywords: "snowman without snow winter holiday" },
			{ emoji: "☄️", keywords: "comet space astronomy shooting meteor" },
			{ emoji: "🔥", keywords: "fire hot flame burn heat lit" },
			{ emoji: "💧", keywords: "droplet water rain drop tear sweat" },
			{ emoji: "🌊", keywords: "water wave ocean sea surf tsunami" },
		],
	},

	{
		name: "Foods",
		emojis: [
			{ emoji: "🍎", keywords: "red apple fruit healthy snack sweet" },
			{ emoji: "🍐", keywords: "pear fruit healthy sweet green" },
			{ emoji: "🍊", keywords: "tangerine orange fruit citrus" },
			{ emoji: "🍋", keywords: "lemon fruit citrus sour yellow" },
			{ emoji: "🍌", keywords: "banana fruit peel yellow" },
			{ emoji: "🍉", keywords: "watermelon fruit summer juicy sweet" },
			{ emoji: "🍇", keywords: "grapes fruit wine vineyard purple" },
			{ emoji: "🍓", keywords: "strawberry fruit red sweet berry" },
			{ emoji: "🫐", keywords: "blueberries fruit berries blue" },
			{ emoji: "🍈", keywords: "melon fruit honeydew cantaloupe" },
			{ emoji: "🍒", keywords: "cherries fruit sweet red berries" },
			{ emoji: "🍑", keywords: "peach fruit sweet juicy" },
			{ emoji: "🥭", keywords: "mango fruit tropical sweet" },
			{ emoji: "🍍", keywords: "pineapple fruit tropical" },
			{ emoji: "🥥", keywords: "coconut fruit tropical beach" },
			{ emoji: "🥝", keywords: "kiwi fruit green healthy" },
			{ emoji: "🍅", keywords: "tomato vegetable fruit red" },
			{ emoji: "🍆", keywords: "eggplant vegetable purple" },
			{ emoji: "🥑", keywords: "avocado fruit vegetable guacamole" },
			{ emoji: "🫒", keywords: "olive vegetable green mediterranean" },
			{ emoji: "🥦", keywords: "broccoli vegetable green healthy" },
			{ emoji: "🥬", keywords: "leafy green vegetable salad lettuce kale" },
			{ emoji: "🥒", keywords: "cucumber vegetable green pickle" },
			{ emoji: "🌶️", keywords: "hot pepper vegetable spicy chili" },
			{ emoji: "🫑", keywords: "bell pepper vegetable green red yellow" },
			{ emoji: "🌽", keywords: "ear of corn vegetable maize" },
			{ emoji: "🥕", keywords: "carrot vegetable orange" },
			{ emoji: "🧄", keywords: "garlic vegetable spice ingredient" },
			{ emoji: "🧅", keywords: "onion vegetable ingredient" },
			{ emoji: "🥔", keywords: "potato vegetable starch" },
			{ emoji: "🍠", keywords: "roasted sweet potato vegetable" },
			{ emoji: "🥐", keywords: "croissant bread pastry french breakfast" },
			{ emoji: "🥯", keywords: "bagel bread breakfast sandwich" },
			{ emoji: "🍞", keywords: "bread loaf wheat sandwich toast" },
			{ emoji: "🥖", keywords: "baguette bread french long" },
			{ emoji: "🥨", keywords: "pretzel bread twisted salt" },
			{ emoji: "🧀", keywords: "cheese wedge dairy milk yellow" },
			{ emoji: "🥚", keywords: "egg breakfast dairy protein" },
			{ emoji: "🍳", keywords: "cooking frying pan breakfast eggs" },
			{ emoji: "🧈", keywords: "butter dairy fat ingredient" },
			{ emoji: "🥞", keywords: "pancakes breakfast flat syrup" },
			{ emoji: "🧇", keywords: "waffle breakfast grid syrup" },
			{ emoji: "🥓", keywords: "bacon meat breakfast pork" },
			{ emoji: "🥩", keywords: "cut of meat steak beef protein" },
			{ emoji: "🍗", keywords: "poultry leg chicken meat turkey" },
			{ emoji: "🍖", keywords: "meat on bone protein dinner" },
			{ emoji: "🦴", keywords: "bone dog meat remain" },
			{ emoji: "🌭", keywords: "hot dog sausage fast food" },
			{ emoji: "🍔", keywords: "hamburger burger fast food beef" },
			{ emoji: "🍟", keywords: "french fries potatoes fast food" },
			{ emoji: "🍕", keywords: "pizza italian cheese pepperoni" },
			{ emoji: "🫓", keywords: "flatbread pita wrap" },
			{ emoji: "🥪", keywords: "sandwich lunch bread toast" },
			{ emoji: "🥙", keywords: "stuffed flatbread gyro falafel" },
			{ emoji: "🧆", keywords: "falafel middle eastern chickpea" },
			{ emoji: "🌮", keywords: "taco mexican food tortilla" },
			{ emoji: "🌯", keywords: "burrito mexican food wrap" },
			{ emoji: "🫔", keywords: "tamale mexican food corn" },
			{ emoji: "🥗", keywords: "green salad healthy vegetable lettuce" },
			{ emoji: "🥘", keywords: "shallow pan of food paella casserole" },
			{ emoji: "🫕", keywords: "fondue cheese chocolate pot dipping" },
			{ emoji: "🥫", keywords: "canned food preserved ready" },
			{ emoji: "🍝", keywords: "spaghetti pasta noodles italian" },
			{ emoji: "🍜", keywords: "steaming bowl ramen soup noodles" },
			{ emoji: "🍲", keywords: "pot of food stew soup" },
			{ emoji: "🍛", keywords: "curry rice spicy indian asian" },
			{ emoji: "🍣", keywords: "sushi japanese fish raw" },
			{ emoji: "🍱", keywords: "bento box japanese lunch meal" },
			{ emoji: "🥟", keywords: "dumpling asian potsticker gyoza" },
			{ emoji: "🦪", keywords: "oyster seafood shellfish" },
			{ emoji: "🍤", keywords: "fried shrimp seafood tempura" },
			{ emoji: "🍙", keywords: "rice ball japanese snack onigiri" },
			{ emoji: "🍚", keywords: "cooked rice grain asian food" },
			{ emoji: "🍘", keywords: "rice cracker japanese snack" },
			{ emoji: "🍥", keywords: "fish cake japanese swirl food" },
			{ emoji: "🥠", keywords: "fortune cookie prediction message" },
			{ emoji: "🥮", keywords: "moon cake chinese festival sweet" },
			{ emoji: "🍢", keywords: "oden japanese skewer food" },
			{ emoji: "🍡", keywords: "dango japanese skewer sweet mochi" },
			{ emoji: "🍧", keywords: "shaved ice dessert cold frozen" },
			{ emoji: "🍨", keywords: "ice cream dessert sweet cold" },
			{ emoji: "🍦", keywords: "soft ice cream cone sweet dessert" },
			{ emoji: "🥧", keywords: "pie dessert pastry apple pumpkin" },
			{ emoji: "🧁", keywords: "cupcake dessert sweet frosting" },
			{ emoji: "🍰", keywords: "shortcake dessert slice sweet" },
			{ emoji: "🎂", keywords: "birthday cake celebration sweet" },
			{ emoji: "🍮", keywords: "custard dessert pudding sweet" },
			{ emoji: "🍭", keywords: "lollipop candy sweet sucker" },
			{ emoji: "🍬", keywords: "candy sweet sugar treats" },
			{ emoji: "🍫", keywords: "chocolate bar candy sweet dessert" },
			{ emoji: "🍿", keywords: "popcorn movie theater snack" },
			{ emoji: "🍩", keywords: "doughnut donut sweet breakfast" },
			{ emoji: "🍪", keywords: "cookie sweet chocolate dessert" },
			{ emoji: "🌰", keywords: "chestnut food nut seed" },
			{ emoji: "🥜", keywords: "peanuts nuts legumes snack" },
			{ emoji: "🍯", keywords: "honey pot sweet bee syrup" },
			{ emoji: "🥛", keywords: "glass of milk dairy drink calcium" },
			{ emoji: "🍼", keywords: "baby bottle milk infant" },
			{ emoji: "🫖", keywords: "teapot tea coffee hot brew" },
			{ emoji: "☕", keywords: "hot beverage coffee tea caffeine" },
			{ emoji: "🍵", keywords: "teacup without handle green tea hot" },
			{ emoji: "🧃", keywords: "beverage box juice drink straw" },
			{ emoji: "🥤", keywords: "cup with straw soda drink cola" },
			{ emoji: "🧋", keywords: "bubble tea boba milk drink" },
			{ emoji: "🍶", keywords: "sake japanese alcohol drink rice" },
			{ emoji: "🍺", keywords: "beer mug alcohol drink pub" },
			{ emoji: "🍻", keywords: "clinking beer mugs alcohol cheers" },
			{ emoji: "🥂", keywords: "clinking glasses champagne wine toast" },
			{ emoji: "🍷", keywords: "wine glass alcohol drink red white" },
			{ emoji: "🥃", keywords: "tumbler glass whiskey liquor alcohol" },
			{ emoji: "🍸", keywords: "cocktail glass drink alcohol martini" },
			{ emoji: "🍹", keywords: "tropical drink alcohol beach vacation" },
			{ emoji: "🧉", keywords: "mate drink tea cup straw" },
			{
				emoji: "🍾",
				keywords: "bottle with popping cork celebration champagne",
			},
			{ emoji: "🧊", keywords: "ice cube cold freeze chill" },
		],
	},
];
